=== wpscanteam/wpscan/data/local_vulnerable_files.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="preserve" />
      <xs:minLength value="1" />
      <xs:pattern value="[^\s].+[^\s]|[^\s]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="uritype">
    <xs:restriction base="xs:anyURI">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="sha1type">
    <xs:restriction base="stringtype">
      <xs:pattern value="[0-9a-f]{40}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="hashtype">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="title" type="stringtype"/>
      <xs:element name="file" type="stringtype"/>
      <xs:element name="reference" type="uritype"/>
    </xs:sequence>
    <xs:attribute type="sha1type" name="sha1" use="required"/>
  </xs:complexType>

  <xs:element name="hashes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hash" type="hashtype" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== wpscanteam/wpscan/data/local_vulnerable_files.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
# WPScan - WordPress Security Scanner
# Copyright (C) 2012-2013
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<!--
  Only he following extensions are scanned : js, php, swf, html, htm
  If you want to add one, modify the variable file_extension_to_scan, line 191 in wpstools.rb
-->

<hashes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="local_vulnerable_files.xsd">

  <hash sha1="17c372678aafb3bc1a7b37320b5cc1d8af433527">
    <title>XSS in swfupload.swf</title>
    <file>swfupload.swf</file>
    <reference>http://brindi.si/g/blog/vulnerable-swf-bundled-in-wordpress-plugins.html</reference>
  </hash>

  <hash sha1="775dc1089829ef07838406def28a4d8bfef69d66">
    <title>Arbitrary File Upload Vulnerability</title>
    <file>php.php</file>
    <reference>http://packetstormsecurity.com/files/119241/wpvalums-shell.txt</reference>
  </hash>

  <!-- This one a is the same as above, but the postSize verification has been removed -->
  <hash sha1="5e8f0d5a917d2937318a9bafd0529135bd473e70">
    <title>Arbitrary File Upload Vulnerability</title>
    <file>php.php</file>
    <reference>http://packetstormsecurity.com/files/119218/wpreflexgallery-shell.txt</reference>
  </hash>

  <hash sha1="3f9ad05b05b65ee2b6efa1373f708293dd2005c7">
    <title>Arbitrary File Upload Vulnerability</title>
    <file>uploadify.php</file>
    <reference>http://packetstormsecurity.com/files/119219/wpuploader104-shell.txt</reference>
  </hash>

  <hash sha1="ac638cc38f011b74a8d9a4e7d3d60358e472166c">
    <title>Inline phpinfo()</title>
    <file>phpinfo.php</file>
    <reference>http://php.net/manual/en/function.phpinfo.php</reference>
  </hash>

  <hash sha1="012ee25cceff745e681fbb3697a06f3712f55554">
    <title>phpinfo()</title>
    <file>phpinfo.php</file>
    <reference>http://php.net/manual/en/function.phpinfo.php</reference>
  </hash>

</hashes>
