=== wpscanteam/wpscan/data/wp_versions.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
# WPScan - WordPress Security Scanner
# Copyright (C) 2012-2013
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="filetype">
    <xs:sequence>
      <xs:element name="hash" type="hashtype" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="stringtype" name="src" use="required"/>
  </xs:complexType>

  <xs:simpleType name="md5type">
    <xs:restriction base="stringtype">
      <xs:pattern value="[0-9a-f]{32}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="hashtype">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="version" type="stringtype"/>
    </xs:sequence>
    <xs:attribute type="md5type" name="md5" use="required"/>
  </xs:complexType>

  <xs:element name="wp-versions">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="file" type="filetype" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== wpscanteam/wpscan/data/wp_versions.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  This file contains identification data to identify WordPress versions.
  http://wordpress.org/download/release-archive/

  Position is important, DO NOT change anything unless you know what you are doing :p
-->

<wp-versions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="wp_versions.xsd">

  <file src="readme.html">
    <hash md5="dfb2d2be1648ee220bf9bd3c03694ed8">
      <version>3.9.2</version>
    </hash>
    <hash md5="cdbf9b18e3729b3553437fc4e9b6baad">
      <version>3.9.1</version>
    </hash>
    <hash md5="84b54c54aa48ae72e633685c17e67457">
      <version>3.9</version>
    </hash>
    <hash md5="fb73e4ab558adc3948adf2653e28d880">
      <version>3.8.4</version>
    </hash>
    <hash md5="c6de8fc70a18be7e5c36198cd0f99a64">
      <version>3.8.3</version>
    </hash>
    <hash md5="e01a2663475f6a7a8363a7c75a73fe23">
      <version>3.8.2</version>
    </hash>
    <hash md5="0d0eb101038124a108f608d419387b92">
      <version>3.8.1</version>
    </hash>
    <hash md5="38ee273095b8f25b9ffd5ce5018fc4f0">
      <version>3.8</version>
    </hash>
    <hash md5="dc09e38cb48fbbec5b5f990513b491e4">
      <version>3.7.4</version>
    </hash>
    <hash md5="813e06052daa0692036e60d76d7141d3">
      <version>3.7.3</version>
    </hash>
    <hash md5="b3a05c7a344c2f53cb6b680fd65a91e8">
      <version>3.7.2</version>
    </hash>
    <hash md5="e82f4fe7d3c1166afb4c00856b875f16">
      <version>3.6.1</version>
    </hash>
    <hash md5="477f1e652f31dae76a38e3559c91deb9">
      <version>3.6</version>
    </hash>
    <hash md5="caf7946275c3e885419b1d36b22cb5f3">
      <version>3.5.2</version>
    </hash>
    <hash md5="05d50a04ef19bd4b0a280362469bf22f">
      <version>3.5.1</version>
    </hash>
    <hash md5="066cfc0f9b29ae6d491aa342ebfb1b71">
      <version>3.5</version>
    </hash>
    <hash md5="36b2b72a0f22138a921a38db890d18c1">
      <version>3.3.3</version>
    </hash>
    <hash md5="628419c327ca5ed8685ae3af6f753eb8">
      <version>3.3.2</version>
    </hash>
    <hash md5="c1ed266e26a829b772362d5135966bc3">
      <version>3.3.1</version>
    </hash>
    <hash md5="9ea06ab0184049bf4ea2410bf51ce402">
      <version>3.0</version>
    </hash>
  </file>

  <file src="wp-includes/css/buttons-rtl.css">
    <hash md5="71c13ab1693b45fb3d7712e540c4dfe0">
      <version>3.8</version>
    </hash>
  </file>

  <file src="wp-includes/js/tinymce/wp-tinymce.js.gz">
    <hash md5="1d52314b1767c557b7232ae192c80318">
      <version>3.9</version>
    </hash>
    <!-- Note: 3.7.1 has no unique file (the hash below is the same than the 3.7.2) -->
    <hash md5="44d281b0d84cc494e2b095a6d2202f4d">
      <version>3.7.1</version>
    </hash>
    <hash md5="b0bcf8091516db358ee9c833afd73175">
      <version>3.7</version>
    </hash>
    <hash md5="cf4bbd562430a9bcbe735062be851be1">
      <version>3.6.1</version>
    </hash>
    <hash md5="42ce18e88f1c21d4e991fcd431bcb606">
      <version>3.6</version>
    </hash>
    <hash md5="a58dd12608659503cf087e879e720354">
      <version>3.5.2</version>
    </hash>
    <hash md5="55c80a4794624ce9b94aa3631ad46c0b">
      <version>3.5.1</version>
    </hash>
    <hash md5="8e529a971610d7ebe7851339c5cb3d67">
      <version>3.5</version>
    </hash>
    <hash md5="ff19e44be975f89b647274d85b70f821">
      <version>3.4.2</version>
    </hash>
  </file>

  <file src="wp-admin/js/customize-controls.js">
    <hash md5="aa0d38bd6f590ad8c3126074145b1bf1">
      <version>3.4.1</version>
    </hash>
  </file>

  <file src="wp-includes/js/customize-preview.js">
    <hash md5="da36bc2dfcb13350c799b62de68dfa4b">
      <version>3.4</version>
    </hash>
  </file>

  <file src="wp-includes/js/plupload/plupload.js">
    <hash md5="85199c05db63fcb5880de4af8be7b571">
      <version>3.3.2</version>
    </hash>
  </file>

  <file src="wp-admin/js/common.js">
    <hash md5="4516252d47a73630280869994d510180">
      <version>3.3</version>
    </hash>
  </file>

  <file src="wp-admin/js/wp-fullscreen.js">
    <hash md5="5675f7793f171b6424bf72f9d7bf4d9a">
      <version>3.2.1</version>
    </hash>
    <hash md5="7b423e0b7c9221092737ad5271d09863">
      <version>3.2</version>
    </hash>
  </file>

  <file src="wp-includes/css/admin-bar.css">
    <hash md5="181250fab3a7e2549a7e7fa21c2e6079">
      <version>3.1</version>
    </hash>
  </file>

  <file src="$wp-content$/themes/twentyten/style.css">
    <hash md5="6211e2ac1463bf99e98f28ab63e47c54">
      <version>3.0</version>
    </hash>
  </file>

  <file src="$wp-plugins$/akismet/readme.txt">
    <hash md5="4d5e52da417aa0101054bd41e6243389">
      <version>2.8.6</version>
    </hash>
    <hash md5="58e086dea9d24ed074fe84ba87386c69">
      <version>2.8.5</version>
    </hash>
    <hash md5="48c52025b5f28731e9a0c864c189c2e7">
      <version>2.8.2</version>
    </hash>
  </file>

  <file src="wp-includes/js/wp-ajax-response.js">
    <hash md5="0289d1c13821599764774d55516ab81a">
      <version>2.7.1</version>
    </hash>
  </file>

  <file src="wp-includes/js/thickbox/thickbox.css">
    <hash md5="9c2bd2be0893adbe02a0f864526734c2">
      <version>2.7</version>
    </hash>
  </file>

  <file src="wp-includes/js/tinymce/plugins/wpeditimage/editor_plugin.js">
    <hash md5="5b140ddf0f08034402ae78b31d8a1a28">
      <version>2.6</version>
    </hash>
  </file>

  <file src="wp-includes/js/tinymce/themes/advanced/js/image.js">
    <hash md5="088245408531c58bb52cc092294cc384">
      <version>2.5.1</version>
    </hash>
  </file>

  <file src="wp-includes/js/tinymce/themes/advanced/js/link.js">
    <hash md5="19c6f3118728c38eb7779aab4847d2d9">
      <version>2.5</version>
    </hash>
  </file>

  <file src="wp-includes/js/wp-ajax.js">
    <hash md5="c5dbce0c3232c477033e0ce486c62755">
      <version>2.2</version>
    </hash>
  </file>

  <file src="$wp-content$/themes/default/style.css">
    <hash md5="e44545f529a54de88209ce588676231c">
      <version>2.0.1</version>
    </hash>
    <hash md5="f786f66d3a40846aa22dcdfeb44fa562">
      <version>2.0</version>
    </hash>
  </file>

  <file src="wp-layout.css">
    <hash md5="7140e06c00ed03d2bb3dad7672557510">
      <version>1.2.1</version>
    </hash>
    <hash md5="1bcc9253506c067eb130c9fc4f211a2f">
      <version>1.2-delta</version>
    </hash>
  </file>

  <file src="layout2b.css">
    <hash md5="baec6b6ccbf71d8dced9f1bf67c751e1">
      <version>0.71-gold</version>
    </hash>
  </file>

</wp-versions>
